# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0002_auto_20170711_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchextension',
            name='par_row_id',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='HRrecrut.SearchObject'),
            preserve_default=False,
        ),
    ]
