# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0004_auto_20170711_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherAuth',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('domainName', models.CharField(max_length=100)),
                ('otherUserName', models.CharField(max_length=100)),
                ('otherPass', models.CharField(max_length=100)),
                ('client_id', models.CharField(max_length=100)),
                ('authoCode', models.CharField(max_length=100)),
                ('access_token', models.CharField(max_length=100)),
                ('refresh_token', models.CharField(max_length=100)),
            ],
        ),
    ]
