# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0005_otherauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherauth',
            name='access_token',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='otherauth',
            name='refresh_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
