# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0006_auto_20170711_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherauth',
            name='authoCode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
