# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 00:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0007_auto_20170711_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='VailidValues',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('domainName', models.CharField(max_length=100)),
                ('criterionName', models.CharField(max_length=50)),
                ('rawValue', models.CharField(max_length=50, null=True)),
                ('validValue', models.CharField(max_length=50, null=True)),
                ('expression', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='searchextension',
            unique_together=set([('par_row', 'baseSequence')]),
        ),
        migrations.AlterUniqueTogether(
            name='vailidvalues',
            unique_together=set([('domainName', 'criterionName', 'rawValue', 'validValue', 'expression')]),
        ),
    ]
