# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0008_auto_20170712_0301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchobject',
            unique_together=set([('domainName', 'SearchMode', 'age', 'gender', 'pay', 'parametrs', 'link')]),
        ),
    ]
