# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0009_auto_20170712_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSequence',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('domainName', models.CharField(max_length=100, unique=True)),
                ('baseSequence', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='searchsequence',
            unique_together=set([('baseSequence', 'domainName')]),
        ),
    ]
