# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0010_auto_20170712_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainName', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('loginLink', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RequestHeaders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sectionName', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=200)),
                ('credentials_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRrecrut.Credentials')),
            ],
        ),
        migrations.CreateModel(
            name='SessionData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookieName', models.CharField(max_length=50)),
                ('cookieValue', models.CharField(max_length=100)),
                ('credentials_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRrecrut.Credentials')),
            ],
        ),
        migrations.DeleteModel(
            name='OtherAuth',
        ),
        migrations.AlterField(
            model_name='searchsequence',
            name='domainName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='credentials',
            unique_together=set([('domainName', 'loginLink')]),
        ),
        migrations.AlterUniqueTogether(
            name='sessiondata',
            unique_together=set([('cookieName', 'credentials_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='requestheaders',
            unique_together=set([('sectionName', 'credentials_id')]),
        ),
    ]
