# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0011_auto_20170820_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestheaders',
            old_name='credentials_id',
            new_name='credentials',
        ),
        migrations.RenameField(
            model_name='sessiondata',
            old_name='credentials_id',
            new_name='credentials',
        ),
        migrations.AlterUniqueTogether(
            name='requestheaders',
            unique_together=set([('sectionName', 'credentials')]),
        ),
        migrations.AlterUniqueTogether(
            name='sessiondata',
            unique_together=set([('cookieName', 'credentials')]),
        ),
    ]
