# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0013_auto_20170820_2302'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sessiondata',
            unique_together=set([]),
        ),
    ]
