# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0014_auto_20170821_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('middleName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('expJob', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRrecrut.Resume')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sessiondata',
            unique_together=set([('cookieName', 'credentials')]),
        ),
        migrations.AlterUniqueTogether(
            name='resume',
            unique_together=set([('firstName', 'lastName', 'middleName', 'email')]),
        ),
        migrations.AlterUniqueTogether(
            name='resumelink',
            unique_together=set([('url', 'resume')]),
        ),
    ]
