# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0015_auto_20170825_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('split', models.CharField(max_length=2, null=True)),
                ('shearTo', models.CharField(max_length=2, null=True)),
                ('shearFrom', models.CharField(max_length=2, null=True)),
                ('sequence', models.CharField(max_length=2, null=True)),
                ('regexp', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='schemaparsing',
            old_name='expression',
            new_name='expressions',
        ),
        migrations.AddField(
            model_name='expression',
            name='SchemaParsing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRrecrut.SchemaParsing'),
        ),
    ]
