# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0016_auto_20170826_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domainName', models.CharField(max_length=100)),
                ('descriptions', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='domain',
            unique_together=set([('domainName',)]),
        ),
    ]
