# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0017_auto_20170826_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemaparsing',
            name='attributeName',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schemaparsing',
            name='attributeValue',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
