# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0020_auto_20170826_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schemaparsing',
            name='domainName',
        ),
    ]
