# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 12:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0023_auto_20170826_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaparsing',
            name='domain',
            field=models.ForeignKey(default='21', on_delete=django.db.models.deletion.CASCADE, to='HRrecrut.Domain'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='schemaparsing',
            unique_together=set([('domain', 'context', 'target')]),
        ),
    ]
