# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 12:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0024_auto_20170826_1533'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchobject',
            unique_together=set([('SearchMode', 'age', 'gender', 'pay', 'parametrs', 'link')]),
        ),
    ]
