# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0029_auto_20170826_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchsequence',
            name='domainName',
        ),
        migrations.AddField(
            model_name='searchsequence',
            name='domain',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='HRrecrut.Domain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchsequence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
