# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 12:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0030_auto_20170826_1546'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchsequence',
            unique_together=set([('baseSequence', 'domain')]),
        ),
    ]
