# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0031_auto_20170826_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vailidvalues',
            old_name='row_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='vailidvalues',
            name='domain',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='HRrecrut.Domain'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vailidvalues',
            unique_together=set([('criterionName', 'rawValue', 'validValue', 'expression')]),
        ),
    ]
