# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0032_auto_20170826_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vailidvalues',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='vailidvalues',
            name='domainName',
        ),
        migrations.AlterUniqueTogether(
            name='vailidvalues',
            unique_together=set([('domain', 'criterionName', 'rawValue', 'validValue', 'expression')]),
        ),
    ]
