# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0033_auto_20170826_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='domain',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='HRrecrut.Domain'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='credentials',
            unique_together=set([]),
        ),
    ]
