# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 13:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0034_auto_20170826_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='domainName',
        ),
        migrations.AlterUniqueTogether(
            name='credentials',
            unique_together=set([('domain', 'loginLink')]),
        ),
    ]
