# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0035_auto_20170826_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobTitle', models.CharField(max_length=100)),
                ('ageFrom', models.CharField(max_length=2)),
                ('ageTo', models.CharField(max_length=2)),
                ('payFrom', models.CharField(max_length=7)),
                ('payTo', models.CharField(max_length=7)),
                ('gender', models.CharField(max_length=7)),
                ('expJob', models.CharField(max_length=7)),
            ],
        ),
    ]
