# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0036_searchcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='vailidvalues',
            name='context',
            field=models.CharField(default='RESUME', max_length=7),
            preserve_default=False,
        ),
    ]
