# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0037_vailidvalues_context'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vailidvalues',
            unique_together=set([('domain', 'criterionName', 'rawValue', 'validValue', 'expression', 'context')]),
        ),
    ]
