# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0038_auto_20170826_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchobject',
            name='iterStep',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='searchobject',
            name='iterator',
            field=models.CharField(default='page', max_length=50),
        ),
    ]
