# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-01 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0040_domain_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchobject',
            name='startPosition',
            field=models.IntegerField(default=0),
        ),
    ]
