# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0041_searchobject_startposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='rootLink',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
