# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0042_domain_rootlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='rootLink',
            new_name='rootUrl',
        ),
    ]
