# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0043_auto_20170905_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiondata',
            name='cookieValue',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
