# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-05 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0044_auto_20170905_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentials',
            name='testLink',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
