# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-12 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0045_credentials_testlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemaparsing',
            old_name='attributeName',
            new_name='attrName',
        ),
        migrations.RenameField(
            model_name='schemaparsing',
            old_name='attributeValue',
            new_name='attrVal',
        ),
    ]
