# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0046_auto_20170912_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expression',
            name='sequence',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expression',
            name='shearFrom',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expression',
            name='shearTo',
            field=models.IntegerField(null=True),
        ),
    ]
