# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0047_auto_20170914_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaparsing',
            name='parSchemaParsing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HRrecrut.SchemaParsing'),
        ),
    ]
