# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0048_schemaparsing_parschemaparsing'),
    ]

    operations = [
        migrations.AddField(
            model_name='expression',
            name='join',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='expression',
            name='seqOper',
            field=models.IntegerField(default=1),
        ),
    ]
