# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0049_auto_20170914_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='itemRecord',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='domain',
            name='previewClick',
            field=models.BooleanField(default=False),
        ),
    ]
