# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-16 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0050_auto_20170915_2130'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableColumnHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=40)),
                ('tableName', models.CharField(max_length=40)),
            ],
        ),
    ]
