# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0051_tablecolumnhead'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecolumnhead',
            name='columnName',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
