# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0052_tablecolumnhead_columnname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablecolumnhead',
            old_name='columnName',
            new_name='fieldName',
        ),
    ]
