# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-18 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0053_auto_20170918_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='expJob',
            new_name='experience',
        ),
        migrations.RenameField(
            model_name='searchcard',
            old_name='expJob',
            new_name='experience',
        ),
    ]
