# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0054_auto_20170918_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaparsing',
            name='notAttr',
            field=models.BooleanField(default=False),
        ),
    ]
