# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0055_schemaparsing_notattr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='descriptions',
            field=models.CharField(max_length=1000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domainName',
            field=models.CharField(max_length=100, verbose_name='Домен'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='itemRecord',
            field=models.IntegerField(default=20, verbose_name='Число записей на странице'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='preview',
            field=models.BooleanField(default=False, verbose_name='Предварительный просмотр'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='rootUrl',
            field=models.CharField(max_length=150, null=True, verbose_name='Базовый URL'),
        ),
        migrations.AlterField(
            model_name='searchcard',
            name='gender',
            field=models.CharField(choices=[('female', 'Женский'), ('man', 'Мужской')], max_length=7),
        ),
    ]
