# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0056_auto_20171002_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(max_length=100, verbose_name='Образование'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Эл.Почта'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.CharField(max_length=50, verbose_name='Опыт работы'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='firstName',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(choices=[('female', 'Женский'), ('man', 'Мужской')], max_length=7, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='lastName',
            field=models.CharField(max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='middleName',
            field=models.CharField(max_length=50, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='phone',
            field=models.CharField(max_length=12, verbose_name='Тел.'),
        ),
    ]
