# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0057_auto_20171002_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumelink',
            name='url',
            field=models.URLField(max_length=100),
        ),
    ]
