# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0058_auto_20171002_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemaparsing',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
