# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0059_schemaparsing_inactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list_of_value',
            name='lang_id',
            field=models.CharField(max_length=3, verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='list_of_value',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='list_of_value',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='list_of_value',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='searchcard',
            name='ageFrom',
            field=models.CharField(max_length=2, verbose_name='Возраст от'),
        ),
        migrations.AlterField(
            model_name='searchcard',
            name='ageTo',
            field=models.CharField(max_length=2, verbose_name='Возраст до'),
        ),
        migrations.AlterField(
            model_name='searchcard',
            name='experience',
            field=models.CharField(max_length=7, verbose_name='Требуемый опыт работы'),
        ),
        migrations.AlterField(
            model_name='searchcard',
            name='gender',
            field=models.CharField(choices=[('female', 'Женский'), ('man', 'Мужской')], max_length=7, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='searchcard',
            name='jobTitle',
            field=models.CharField(max_length=100, verbose_name='Вакансия'),
        ),
        migrations.AlterField(
            model_name='searchcard',
            name='payFrom',
            field=models.CharField(max_length=7, verbose_name='Зарплата от'),
        ),
        migrations.AlterField(
            model_name='searchcard',
            name='payTo',
            field=models.CharField(max_length=7, verbose_name='Зарплата до'),
        ),
        migrations.AlterField(
            model_name='searchsequence',
            name='domain',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='searchsequence',
            unique_together=set([]),
        ),
    ]
