# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0060_auto_20171006_0031'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchSequence',
        ),
    ]
