# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0061_delete_searchsequence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchextension',
            old_name='row_id',
            new_name='id',
        ),
        migrations.AlterUniqueTogether(
            name='searchextension',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='searchextension',
            name='par_row',
        ),
    ]
