# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0062_auto_20171006_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchextension',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
