# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 21:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0063_auto_20171006_0038'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchExtension',
        ),
    ]
