# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-06 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0065_auto_20171006_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchcard',
            old_name='payFrom',
            new_name='salaryFrom',
        ),
        migrations.RenameField(
            model_name='searchcard',
            old_name='payTo',
            new_name='salaryTo',
        ),
        migrations.RenameField(
            model_name='searchcard',
            old_name='jobTitle',
            new_name='text',
        ),
    ]
