# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-18 07:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0068_schemaparsing_sequens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchcard',
            name='experience',
        ),
    ]
