# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-11 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0069_remove_searchcard_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.CharField(default='По договоренности', max_length=10, verbose_name='Ожидаемая Зарплата')),
                ('age', models.CharField(max_length=10, null=True, verbose_name='Возраст')),
                ('jobExp', models.CharField(max_length=10, null=True, verbose_name='Опыт работы')),
                ('lastJob', models.CharField(max_length=100, null=True, verbose_name='Последнее место работы')),
                ('jobTitle', models.CharField(max_length=200, null=True, verbose_name='Интересующая должность')),
                ('gender', models.CharField(choices=[('all', 'Неважно'), ('female', 'Женский'), ('man', 'Мужской')], max_length=7, verbose_name='Пол')),
                ('url', models.URLField(max_length=100, verbose_name='Ссылка')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRrecrut.Domain')),
                ('search_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRrecrut.SearchCard')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='searchresult',
            unique_together=set([('url',)]),
        ),
    ]
