# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-11 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0071_auto_20171211_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='gender',
            field=models.CharField(max_length=7, null=True, verbose_name='Пол'),
        ),
    ]
