# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HRrecrut', '0072_auto_20171212_0019'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchcard',
            unique_together=set([('text', 'ageFrom', 'ageTo', 'salaryFrom', 'salaryTo', 'gender')]),
        ),
    ]
